<?

require_once 'helpers.php';


$users = $_POST['user'];
$owner_index = $_POST['owner'];
$group_name = $_POST['group_name'];
$group_desc = 'A group generated by SettleUp - a WePay app helping you settle the debts between you and your friends';
$due = strtotime('next month');

$owner = get_or_create_user($users[$owner_index]['email'], $users[$owner_index]['name']);
if (!$owner) {
	exit_with_error("Could not create owner.");
	exit;
}

$group = create_group($group_name, $group_desc, $owner->user_id);
if (!$group) {
	exit_with_error("Could not create group.");
	exit;
}

$errors = array();
foreach($users as $user) {
	//Make sure we are not the owner since the owner has already been created
	if ($user['email'] != $users[$owner_index]['email']) {
		$wepay_user = get_or_create_user($user['email'], $user['name']);
		if (!$wepay_user) {
			error_log("Failed to create user {$user['name']} {$user['email']}");
			error_log(print_r($_POST, true));
			array_push($errors, 'Could not create user ' . $user['name'] . '.');
			continue;
		}
		
		$invite = invite_user($group, $wepay_user->user_id, $owner->user_id);
		if (!$invite) {
			error_log("Failed to create invite for user {$user['name']} {$user['email']} {$wepay_user->user_id}");
			error_log(print_r($_POST, true));
			array_push($errors, 'Could not invite user ' . $user['name'] . ' to group.');
			continue;
		}
		
		//We cannot request remimbursements from any group a user is not a part of so we make sure the user is in the group
		$result = accept_invite($invite->id, $wepay_user->user_id);
	}
	else {
		$wepay_user = $owner;
	}
	
	//Send bill/reimbursement
	if ($user['debt'] < 0) {
		$bill = send_bill($group->id, $wepay_user->user_id, abs($user['debt']), 'The difference you owe.', $due);
	}
	else {
		$bill = request_money($group->id, $wepay_user->user_id, $user['debt'], 'The difference owed to you.', $due);
	}
		
	if (!isset($bill)) {
		error_log("Failed to create bill for {$user['debt']} {$user['name']} {$user['email']} {$wepay_user->user_id}");
		error_log(print_r($_POST, true));
		array_push($errors, "Could not create bill for {$user['debt']} to {$user['name']}");
		continue;
	}
}

$ret = new stdClass;
if (count($errors) > 0) {
	$ret->error = 1;
	$ret->result = implode(" ", $errors);
}
else {
	$ret->error = 0;
	$ret->registered = $owner->registered;
	$group_url = 'https://www.wepay.com/group/view/' . $group->id;
	if (!$ret->registered) {
		$ret->url = $owner->verify_account_url 
				  . '?em=' . urlencode($users[$owner_index]['email']) 
				  . '&rd=' . urlencode($group_url);
	}
	else {
		$ret->url = $group_url;
	}
}


header('Content-type: application/json');
header("HTTP/1.0 200", null, 200);
echo json_encode($ret);

function exit_with_error($message) {
	error_log($message);
	error_log(print_r($_POST, true));
	$ret = new stdClass;
	$ret->error = 1;
	$ret->result = $message;
	header('Content-type: application/json');
	header("HTTP/1.0 200", null, 200);
	echo json_encode($ret);
	exit;
}
